### ISSUE TITLE
SDK VRCWorld prefab does not have spawn point set

### ISSUE THREAD

**Issue by techanon** [vrchat/packages#6]
(If these should be a canny instead of an issue on github, let me know)

When adding a VRCWorld prefab to the scene after adding the joke jam branch to my project, I noticed the scene descriptor was missing/broken. After running Reload Plugins, it was added, but it also did not have any default spawn point provided. This behavior differs from previous builds where it would explicitly default to referencing its own game object transform.

**Comment by momo-the-monster** [comment]
The latest release has the VRCWorld check whether it has any spawn points, and sets itself as the default spawn point if none are listed. This should fix this issue as well as #7 - thanks!
