### ISSUE TITLE
World SDK does not include VRC_SDK_VRCSDK3 script define symbol, breaking some assets

### ISSUE THREAD

**Issue by CyanLaser** [vrchat/packages#8]
Some assets work for both SDK2 and SDK3, and use the sdk script define symbol to select which logic to use. The new sdk does not provide the symbol for VRC_SDK_VRCSDK3, meaning that any asset that requires this will not work with this version of the sdk. 

As an example, 1's WorldToolkit does not work properly without the script define symbol
https://github.com/oneVR/VRWorldToolkit

Related canny:
https://feedback.vrchat.com/feature-requests/p/world-jam-sdk-add-back-sdk3-define

**Comment by momo-the-monster** [comment]
The fix for this issue was pushed to [#wj3](https://github.com/vrchat/packages/releases/tag/wj3) for the JokeJam. Fixing it upstream for the next release of the SDK as well, will keep this open until then.

**Comment by momo-the-monster** [comment]
Fixed the legacy code which looked in an old place to detect SDKs, this symbol should be added to projects now.
